spring:
  application:
    name: customer-api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:6033}/customerdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
